properties:
  line-separator: <newline>
  chat-prefix: '&7[&aNotes&7] '
  db-type: sqlite
  permission-default: op
  notify-by-default: true
  notes-per-page: 10
  date-format: MM/dd/yy h:mm a
  check-new-version: true
  async-db-queries: true
  confirm-player-joined: true
  auto-note-permission: true
  debug-messages: false
  player-colour: BLUE
  notify-colour: RED
  
  # Let mcstats.org know the plugin's running, so the developer knows how popular the plugin is.
  use-metrics: true
  
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: AN_