name: AdminNotes
main: com.cyprias.AdminNotes.Plugin
author: Cyprias, bmlzootown
description: An Admin notes plugin.
version: 0.12.5
api-version: 1.14

commands:
  notes:
    description: Get available commands